## NumPy - Numeric Python
https://docs.scipy.org/doc/numpy/


NumPy is the fundamental package for scientific computing with Python.
![alt text](images/MATLAB_vs_PYTHON.png "Title")
#### NumPy contains:
* powerful N-dimensional array object
* sophisticated (broadcasting) functions
* tools for integrating C/C++ and Fortran code
* useful linear algebra, Fourier transform, and random number capabilities

## Python List
* Powerful
* Collection of values
* Different values data types - heterogeneous 
* Change, add, remove
* Other Functionalities
* Missing: No calculation on the whole list!

## NumPy array is Alternative to list in core python
* Easy and fast
* Allow calculation on the whole list
* Sub sting and broadcasting
* Differences from lists: same type array. concatenate vs + and other ops
* Similar to list: indexing,...

#### NumPy
* array oriented computing
* efficiently implemented multi-dimensional arrays
* designed for scientific computation

In [1]:
import numpy as np

print(np.__version__)

1.10.1


#### Creation
* array(iter)
* ones()
* zeros()
* arange()
* linspace()
* logspace()

In [2]:
import numpy as np

li = [1,2,3,4]
a = np.array(li)
type(a)
a.dtype
a.ndim

1

In [3]:
A = np.array([ [3.4, 8.7, 9.9], 
               [1.1, -7.8, -0.7],
               [4.1, 12.3, 4.8]])
print(A)
print(A.ndim)

[[  3.4   8.7   9.9]
 [  1.1  -7.8  -0.7]
 [  4.1  12.3   4.8]]
2


In [4]:
#Creation:
arr_1d = np.array([1 ,2 ,3])
arr_2d = np.array([[1 ,2 ,3] ,[11 ,22 ,33]])

np.zeros (8)

np.ones((2 ,3 ,5))
np.arange (10)
np.arange (3.5 ,10 ,2)

#linspace(start, stop, num=50, endpoint=True, retstep=False) #include end point #return spacing (tuple return)
np.linspace (1 ,3 ,5)
np.logspace (1 ,3 ,5)
result,spacing = np.linspace(1,21,10,True,True)
print(spacing,result)

np.identity(4, dtype=int)

2.2222222222222223 [  1.           3.22222222   5.44444444   7.66666667   9.88888889
  12.11111111  14.33333333  16.55555556  18.77777778  21.        ]


array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

### Operators


In [5]:
#+,-,%,*,dot(@)
a , b = np.array ([1 ,2]) , np.array ([10 ,20])
a + b
a * b
a@b
a.dot(b)

50

### Indexing and Slicing
Numpy very powerful and similar to core Python

In [6]:
B = np.array([ [[111, 112], [121, 122]],
               [[211, 212], [221, 222]],
               [[311, 312], [321, 322]] ])
print(B[0][1][0])
print(B[-1])

121
[[311 312]
 [321 322]]


In [7]:
# An alternative: We use only one pair of square brackets and all the indices are separated by commas

print(B[1, 0,1])

212


#### Shaping

In [8]:
a= np.arange(10)
print(a)
print(a.shape)
print(np.shape(a))
a.shape = 2,5
print(a)

[0 1 2 3 4 5 6 7 8 9]
(10,)
(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [9]:
print(a[1:,2:])

[[7 8 9]]


In [10]:
#Slice
X = np.arange(28).reshape(4,7)
print(X)
print(X[::2, ::3])
print(X[:,6:])

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]]
[[ 0  3  6]
 [14 17 20]]
[[ 6]
 [13]
 [20]
 [27]]


In [11]:
a.sum()
a[1:]
a[1:].sum()

35

#### Performance:
* Python list is a C array of pointers to values. Therefore, appending a value is fast, but operating on every value is slow.
* NumPy array is a C array of values. Therefore, appending a value is slow (reallocating), but operating on every value is fast.


In [12]:
import time
size_of_vec = 1000000
def pure_python_version():
    t1 = time.time()
    X = range(size_of_vec)
    Y = range(size_of_vec)
    Z = []
    for i in range(len(X)):
        Z.append(X[i] + Y[i])
    return time.time() - t1

def numpy_version():
    t1 = time.time()
    X = np.arange(size_of_vec)
    Y = np.arange(size_of_vec)
    Z = X + Y
    return time.time() - t1


t1 = pure_python_version()
t2 = numpy_version()
print(t1, t2)
print("Numpy is in this example " + str(t1/t2) + " faster!")

1.5685582160949707 0.015626907348632812
Numpy is in this example 100.37547296472599 faster!


## Universal functions (ufunc)

* A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion
* Many of the built-in functions are implemented in compiled C code
 * Math operations
 * Trigonometric Functions
 * Floating functions
 * Comparison functions
 * fromfunction ... create a ufunc from python function
 
## Powerful Random Generator ... many distributions
 * https://docs.scipy.org/doc/numpy/reference/routines.random.html
 
## Routines
 * Basic statistics: mean, median,std,sum,sort ...
 * https://docs.scipy.org/doc/numpy/reference/routines.html

In [13]:
#Truth array
np.linspace (0 ,5 ,10)
a < 2
np.all (a <2)
np.any (a <2)

True

In [14]:
#From pure Python to NumPy
import math
def func ( x ):
    return math.sin ( x ) * math.exp ( -0.5* x )

x = [0.1* i for i in range (10000001)]
y = [ func ( ix ) for ix in x ]
y


[0.0,
 0.09496448346290234,
 0.17976344431953514,
 0.2543565990681965,
 0.3188287726607408,
 0.37337698488938337,
 0.41829743246183443,
 0.4539725313825362,
 0.4808581678757144,
 0.49947128950136815,
 0.5103779515445728,
 0.5141819173971393,
 0.5115138956732544,
 0.5030214813605536,
 0.48935985353748196,
 0.47118326819860185,
 0.4491373716135583,
 0.4238523474754888,
 0.39593689992533637,
 0.36597306440731486,
 0.33451182923926226,
 0.30206954277677284,
 0.2691250741054271,
 0.236117689292758,
 0.20344560034181325,
 0.17146514007298644,
 0.14049051317399683,
 0.11079407154662793,
 0.08260706078486106,
 0.056120784079971585,
 0.03148812999854588,
 0.008825411351839677,
 -0.011785536298949018,
 -0.030295046145528325,
 -0.04668314905858101,
 -0.06095698477190062,
 -0.07314813729196273,
 -0.08330993340699941,
 -0.09151473990877614,
 -0.0978512917665222,
 -0.10242208005667372,
 -0.10534082500098385,
 -0.10673005604160185,
 -0.10671881752302714,
 -0.10544051529110539,
 -0.10303091638776922,


In [15]:
import numpy as np
def func ( x ):
    return np . sin ( x ) * np . exp ( -0.5* x )
x = np.linspace (0 ,10 ,10000001)
y = func (x)
y

array([  0.00000000e+00,   9.99999500e-07,   1.99999800e-06, ...,
        -3.66557777e-03,  -3.66558159e-03,  -3.66558541e-03])